id: ABAE244D1
title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for Saving
  Lives'
type: translation
pechas:
- IB65555E1
- I12CAED87
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:12:00.034181
  last_modified_at: 2023-01-04 13:12:00.034188
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IB65555E1/E102: BBE0
  I12CAED87/D0D8: BBE0
